name: push_notification
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_messaging: ^13.0.3
  stacked: ^3.0.0
  firebase_core: ^1.23.0
  overlay_support: ^2.0.1
  cached_network_image: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/svg/
    - assets/png/
  fonts:
    - family: LatoBlack
      fonts:
        - asset: assets/font/lato_black/Lato-Light.ttf
          weight: 300
        - asset: assets/font/lato_black/Lato-Regular.ttf
          weight: 400
        - asset: assets/font/lato_black/Lato-Bold.ttf
          weight: 700
        - asset: assets/font/lato_black/Lato-Black.ttf
          weight: 900